# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [ ]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
import numpy as np
A = np.arange(1, 16).reshape(3,5)


In [4]:
A.shape

(3, 5)

In [5]:
A.ndim

2

In [6]:
A.dtype.name

'int64'

In [7]:
A.itemsize

8

In [8]:
A.size

15

In [9]:
type(A)

numpy.ndarray

In [12]:
A = np.array([[1, 1],

              [0, 1]])

B = np.array([[2, 0],

              [3, 4]])
A * B 


array([[2, 0],
       [0, 4]])

In [13]:
A @ B

array([[5, 4],
       [3, 4]])

In [14]:
A.dot(B)

array([[5, 4],
       [3, 4]])

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [15]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [27]:
A = B - C
print (A)

D = B * C
print(D)

E = B @ C
print (E)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


In [20]:
import numpy as np
a = np.ones(3, dtype=np.int32)

b = np.linspace(0, np.pi, 3)

b.dtype.name

'float64'

In [21]:
a [ : 3] * 2

array([2, 2, 2], dtype=int32)

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [28]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
D = np.exp(B)
print(D)
B.min()
B.min(axis=1)
B.min(axis = 0)
np.argmin(B)
np.argmin(B,axis= 0)
np.sum(B)
np.mean(B,axis=0)
np.median(B,axis=0)

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


array([4., 5., 6.])

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [ ]:
print(A)

In [ ]:
A[1]

**Answer:**

When fewer indices are provided than the number of axes, the missing indices are considered complete slices:
b[-1]   # the last row. Equivalent to b[-1, :]


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [ ]:
A

In [55]:
for i in A:
    print(i)

[-1.  0.  1.]
[2. 3. 4.]
[5. 6. 7.]


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [56]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


a = np.arange(30): a creates 0 to 29 elements of an array.
b = a.reshape((2, 3, -1)):b



### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [57]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [58]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [59]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [2]:
import numpy as np

def add_mult_matrices(matrix1, matrix2, operation):

    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        raise ValueError("Both inputs must be of type numpy.ndarray.")

    if operation not in ['add', 'multiply']:
        raise ValueError("Operation must be either 'add' or 'multiply'.")
    
    if operation == 'add':
        if matrix1.shape != matrix2.shape:
            raise ValueError("Matrices must have the same dimensions for addition.")
        return matrix1 + matrix2
    
    elif operation == 'multiply':
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("Number of columns in the first matrix must equal the number of rows in the second matrix for multiplication.")
        return np.dot(matrix1, matrix2)

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

print("Addition:")
print(add_mult_matrices(matrix1, matrix2, 'add'))


print("Multiplication:")
print(add_mult_matrices(matrix1, matrix2, 'multiply'))


Addition:
[[ 6  8]
 [10 12]]
Multiplication:
[[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

Uppgift 10.1.1:
x = (4,3) enlight
a. Vilken dimension har vektorn x?
svar: Jag ser vektorn har 2 komponenter, så vektorn har 2 dimension.

b. Beräkna 5x?
svar : 5*x = 5 * (4,3) = ( 20, 15)
 
c.Beräkna 3x 
svar: 3*x = 3*(4,3) = (12 , 9)

d. Beräkna 5x + 3x
svar: 5*(4,3) + 3*(4,3) = (20,15) + (12,9) = (32 , 24)

e. Beräkna 8x
svar : 8*x = 8*(4,3) = (32,24)

f. Beräkna 4x-x
svar : 4x-x = 4*(4,3) - (4,3) = (16 , 12)-(4,3) =(12 ,9)

g. Beräkna x^T,vilket blir nya dimension efter att transponeringen utfört?

svar : Vector x = (4,3), Så den har dimensionen 1 × 2, eftersom det är en radvektor med 1 rad och 2 kolumner. x^T =(4/3) Efter transponering blir x ^ T en kolumnvektor  med dimensionen  2 x 1 är 2 rader och 1 kolumn. Efter transponering av 𝑥 blir den nya dimensionen 2 × 1.

h. Är x + x^ T definerat.
svar: Nej. Rad och Kolumn dimensionen matcher inte på vektor och Rad och Kolumn vektor definerar inte i matris. 

i. Beräkna || X ||.

svar: x=(4,3) så Root 4^2 + Root 3^2 = Root25 = 5


10.1.2. Definera vektorn har vektorn v?
V = (3
     7
     0
     11 )

a. Vilken dimension har vektorn v?

svar: Vektorn har 4 komponenter så vektor har 4 dimonsion.

b. Beräkna  2v.

svar: 2v = ( 6
            14
             0
            22)

c. Beräkna 5v + 2v

svar: 5v + 2v = (21
                 49
                 0
                 77)

d. Beräkna 4v - 2v

svar: 4v -2v = (6
                14
                0
                22)

e. Beräkna V^T vilken blir nya diamension.

svar: V^T = (3,7,0,11)
Nya dimension blir 1x4.

f. Beräkna || v ||

svar: || v || = Rooyt(3^2 + 7^2 + 11^2) = Root(179) = 13.38



Uppgift 10.1.3.

a. Beräkna  || v1 || 
svar : v1 = root(4^1 + 3^2 + 1.5^2) = root(27.25) = 5.22   

b. Beräkna || v1 - v2 ||
svar: || v1 - v2 || = root(4.16) ~~ 2.04


Uppgift 10.2.1. Definera matriserna

a. Svar: 2A = 2.(2 1 -1)
                (1 1 1)
                (-1 0 1)
            = (4 1 -2)  
              (2 2 2) 
              (-2 0 2) 

b. B -2A
svar: B är en 2 x 3 matris och 2A är 3 x 3 matris.

c. 3C -2E
Svar:C är 2 x 2 matris och E är 1 X 1 vektor. Inte definerat så dimension matchar inte.

d. 2D-3C
Svar: 2D - 3c = (6  8)   -  (1.5 1.5)
                (6  6)       (1.5 1.5)
              

              = (4.5   6.5)
                (4.5   4.5)



e. D^T + 2D 
Svar: D^T + 2D = (9   11)
                 (10   9)




f. 2C^T -2D^T
Svar: 2C^T -2D^T =  ( 2  4 
                      4  2) - (6  8
                               8  6)
                =( −4  −4
                   −4  −4)
​

g.A^T - B

Svar:A^T = ( 2   1   -1)
           (1    1   0)
           (-1   1    1)

matris B är 2 X 3 och A^T 3 X 3. Dimension matchar inte och inte definerat.

h. AC = (4   5
        −1   1
         1  -1)

i. CD = (11   10
         10   11)
        

j.CB = (8  −10   -3
        10   8    0)

k.CI = (1   2
        2   1)


l. AB^T =  (5    2
            7    4)

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [60]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [61]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [62]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
